//! C backend: walks the Mott AST and emits portable C11.
//!
//! Notes on the runtime contract (see `runtime/mott_rt.h`):
//! - `terah` maps to `int64_t`, `daqosh` to `double`, `bool` to `bool`,
//!   `deshnash` to `mott_str` (struct with `data` + `len`).
//! - String interpolation is lowered to a `mott_str_build(parts, n)` call
//!   that concatenates into a heap-allocated (leaked) buffer.
//! - `yazde` is dispatched at codegen time to the per-type runtime helper
//!   (`mott_yazde_terah`, etc.) — the language surface has one `yazde` but
//!   C needs a monomorphic function.
//!
//! Type handling is deliberately minimal here (MVP): we do inline inference
//! during emission so a `xilit x = 5;` doesn't require a separate sema pass.
//! v0.2 will lift this into a real checker.

use std::collections::HashMap;
use std::fmt::Write as _;

use crate::ast::{BinOp, Block, Expr, Function, Item, Program, Stmt, Type, UnOp};
use crate::codegen::Backend;
use crate::error::{Error, Result};
use crate::token::StringPart;

pub struct CBackend;

impl Backend for CBackend {
    fn name(&self) -> &'static str {
        "c"
    }

    fn emit(&self, program: &Program) -> Result<String> {
        let mut e = Emitter::new(program)?;
        e.emit_program(program)?;
        Ok(e.out)
    }
}

#[derive(Debug, Clone)]
struct FuncSig {
    params: Vec<Type>,
    return_type: Option<Type>,
}

struct Emitter {
    out: String,
    indent: usize,
    scopes: Vec<HashMap<String, Type>>,
    functions: HashMap<String, FuncSig>,
    /// Depth of enclosing `cqachunna` loops. Used to validate that `sac` and
    /// `khida` only appear inside a loop — outside, they'd generate C that
    /// clang would reject, but we want to catch it with a mott-level error.
    loop_depth: usize,
}

impl Emitter {
    fn new(program: &Program) -> Result<Self> {
        let mut functions = HashMap::new();
        for item in &program.items {
            let Item::Function(f) = item;
            let sig = FuncSig {
                params: f.params.iter().map(|p| p.ty).collect(),
                return_type: f.return_type,
            };
            if functions.insert(f.name.clone(), sig).is_some() {
                return Err(Error::Codegen(format!(
                    "duplicate function `{}`",
                    f.name
                )));
            }
        }
        Ok(Self {
            out: String::new(),
            indent: 0,
            scopes: Vec::new(),
            functions,
            loop_depth: 0,
        })
    }

    fn emit_program(&mut self, program: &Program) -> Result<()> {
        self.write_prelude();

        // Forward-declare every non-entry function so call-before-define works.
        let mut has_decls = false;
        for item in &program.items {
            let Item::Function(f) = item;
            if f.name == "kort" {
                continue;
            }
            self.emit_function_signature(f);
            self.writeln(";");
            has_decls = true;
        }
        if has_decls {
            self.writeln("");
        }

        for item in &program.items {
            let Item::Function(f) = item;
            self.emit_function(f)?;
            self.writeln("");
        }
        Ok(())
    }

    fn write_prelude(&mut self) {
        self.writeln("/* Generated by mott compiler v0.1 — do not edit. */");
        self.writeln("#include <stdbool.h>");
        self.writeln("#include <stdint.h>");
        self.writeln("#include \"mott_rt.h\"");
        self.writeln("");
    }

    fn emit_function_signature(&mut self, f: &Function) {
        let ret = match f.return_type {
            Some(t) => type_to_c(t),
            None => "void",
        };
        self.write(&format!("{} {}(", ret, f.name));
        if f.params.is_empty() {
            self.write("void");
        } else {
            for (i, p) in f.params.iter().enumerate() {
                if i > 0 {
                    self.write(", ");
                }
                self.write(&format!("{} {}", type_to_c(p.ty), p.name));
            }
        }
        self.write(")");
    }

    fn emit_function(&mut self, f: &Function) -> Result<()> {
        if f.name == "kort" {
            if !f.params.is_empty() {
                return Err(Error::Codegen(
                    "entry function `kort` must not take parameters".into(),
                ));
            }
            if f.return_type.is_some() {
                return Err(Error::Codegen(
                    "entry function `kort` must not declare a return type".into(),
                ));
            }
            self.write("int main(void)");
        } else {
            self.emit_function_signature(f);
        }
        self.writeln(" {");
        self.indent += 1;
        self.push_scope();
        for p in &f.params {
            self.declare(&p.name, p.ty);
        }
        for s in &f.body.stmts {
            self.emit_stmt(s)?;
        }
        if f.name == "kort" {
            self.write_indent();
            self.writeln("return 0;");
        }
        self.pop_scope();
        self.indent -= 1;
        self.writeln("}");
        Ok(())
    }

    /// Emit `if (cond) {...} [else ...]` without a leading indent, collapsing
    /// parser-desugared `khi nagah sanna` chains back into idiomatic C
    /// `else if`. Parser wraps each chained condition in a single-stmt block
    /// — we detect that shape and recurse instead of nesting braces.
    fn emit_if_chain(
        &mut self,
        cond: &Expr,
        then_block: &Block,
        else_block: Option<&Block>,
    ) -> Result<()> {
        self.write("if (");
        let ct = self.emit_expr(cond)?;
        if ct != Type::Bool {
            return Err(Error::Codegen(format!(
                "`nagah sanna` condition must be bool, got {}",
                type_name(ct)
            )));
        }
        self.write(")");
        self.emit_block_inline(then_block)?;
        if let Some(eb) = else_block {
            if let Some((c2, t2, e2)) = as_chained_if(eb) {
                self.write(" else ");
                self.emit_if_chain(c2, t2, e2)?;
            } else {
                self.write(" else");
                self.emit_block_inline(eb)?;
            }
        }
        Ok(())
    }

    /// Emit `{ ... }` for a control-flow body. Assumes the caller already
    /// wrote everything up to (but not including) the opening brace.
    fn emit_block_inline(&mut self, b: &Block) -> Result<()> {
        self.writeln(" {");
        self.indent += 1;
        self.push_scope();
        for s in &b.stmts {
            self.emit_stmt(s)?;
        }
        self.pop_scope();
        self.indent -= 1;
        self.write_indent();
        self.write("}");
        Ok(())
    }

    fn emit_stmt(&mut self, s: &Stmt) -> Result<()> {
        match s {
            Stmt::Let { name, ty, value } => {
                self.write_indent();
                let actual_ty = match ty {
                    Some(t) => *t,
                    None => self.infer(value)?,
                };
                if self.scopes.last().unwrap().contains_key(name) {
                    return Err(Error::Codegen(format!(
                        "variable `{}` already declared in this scope",
                        name
                    )));
                }
                self.write(&format!("{} {} = ", type_to_c(actual_ty), name));
                let val_ty = self.emit_expr(value)?;
                if ty.is_some() && val_ty != actual_ty {
                    return Err(Error::Codegen(format!(
                        "type mismatch: `{}` declared as {} but initializer is {}",
                        name,
                        type_name(actual_ty),
                        type_name(val_ty)
                    )));
                }
                self.writeln(";");
                self.declare(name, actual_ty);
            }
            Stmt::Assign { name, value } => {
                let target_ty = self.lookup(name).ok_or_else(|| {
                    Error::Codegen(format!("assignment to undefined variable `{}`", name))
                })?;
                self.write_indent();
                self.write(&format!("{} = ", name));
                let val_ty = self.emit_expr(value)?;
                if val_ty != target_ty {
                    return Err(Error::Codegen(format!(
                        "type mismatch: `{}` is {} but value is {}",
                        name,
                        type_name(target_ty),
                        type_name(val_ty)
                    )));
                }
                self.writeln(";");
            }
            Stmt::If {
                cond,
                then_block,
                else_block,
            } => {
                self.write_indent();
                self.emit_if_chain(cond, then_block, else_block.as_ref())?;
                self.writeln("");
            }
            Stmt::While { cond, body } => {
                self.write_indent();
                self.write("while (");
                let ct = self.emit_expr(cond)?;
                if ct != Type::Bool {
                    return Err(Error::Codegen(format!(
                        "`cqachunna` condition must be bool, got {}",
                        type_name(ct)
                    )));
                }
                self.write(")");
                self.loop_depth += 1;
                let body_result = self.emit_block_inline(body);
                self.loop_depth -= 1;
                body_result?;
                self.writeln("");
            }
            Stmt::Break => {
                if self.loop_depth == 0 {
                    return Err(Error::Codegen(
                        "`sac` outside of `cqachunna` loop".into(),
                    ));
                }
                self.write_indent();
                self.writeln("break;");
            }
            Stmt::Continue => {
                if self.loop_depth == 0 {
                    return Err(Error::Codegen(
                        "`khida` outside of `cqachunna` loop".into(),
                    ));
                }
                self.write_indent();
                self.writeln("continue;");
            }
            Stmt::Return(e) => {
                self.write_indent();
                match e {
                    Some(expr) => {
                        self.write("return ");
                        self.emit_expr(expr)?;
                        self.writeln(";");
                    }
                    None => self.writeln("return;"),
                }
            }
            Stmt::Print(e) => {
                let ty = self.infer(e)?;
                let helper = match ty {
                    Type::Terah => "mott_yazde_terah",
                    Type::Daqosh => "mott_yazde_daqosh",
                    Type::Bool => "mott_yazde_bool",
                    Type::Deshnash => "mott_yazde_deshnash",
                };
                self.write_indent();
                self.write(&format!("{}(", helper));
                self.emit_expr(e)?;
                self.writeln(");");
            }
            Stmt::ExprStmt(e) => {
                self.write_indent();
                self.emit_expr(e)?;
                self.writeln(";");
            }
        }
        Ok(())
    }

    /// Emit an expression and return its type. Always wraps in parens so
    /// precedence never bites us — the C compiler will clean it up.
    fn emit_expr(&mut self, e: &Expr) -> Result<Type> {
        match e {
            Expr::Integer(n) => {
                // INT64_MIN cannot be written as a single negated literal in C.
                if *n == i64::MIN {
                    self.write("((int64_t)(-9223372036854775807LL - 1))");
                } else {
                    self.write(&format!("((int64_t){}LL)", n));
                }
                Ok(Type::Terah)
            }
            Expr::Float(f) => {
                // {:?} preserves enough precision to round-trip.
                // Force a decimal point so the literal is always interpreted as double.
                let s = format!("{:?}", f);
                let s = if s.contains('.') || s.contains('e') || s.contains("inf") || s.contains("nan") {
                    s
                } else {
                    format!("{}.0", s)
                };
                self.write(&s);
                Ok(Type::Daqosh)
            }
            Expr::Bool(b) => {
                self.write(if *b { "true" } else { "false" });
                Ok(Type::Bool)
            }
            Expr::Ident(name) => {
                let ty = self.lookup(name).ok_or_else(|| {
                    Error::Codegen(format!("use of undefined variable `{}`", name))
                })?;
                self.write(name);
                Ok(ty)
            }
            Expr::String(parts) => {
                self.emit_string_expr(parts)?;
                Ok(Type::Deshnash)
            }
            Expr::Binary { op, left, right } => {
                self.write("(");
                let lt = self.emit_expr(left)?;
                self.write(bin_op_str(*op));
                let rt = self.emit_expr(right)?;
                self.write(")");
                match op {
                    BinOp::Add | BinOp::Sub | BinOp::Mul | BinOp::Div | BinOp::Mod => {
                        if lt != rt {
                            return Err(Error::Codegen(format!(
                                "arithmetic type mismatch: {} vs {}",
                                type_name(lt),
                                type_name(rt)
                            )));
                        }
                        if !matches!(lt, Type::Terah | Type::Daqosh) {
                            return Err(Error::Codegen(format!(
                                "arithmetic on non-numeric type {}",
                                type_name(lt)
                            )));
                        }
                        if matches!(op, BinOp::Mod) && lt != Type::Terah {
                            return Err(Error::Codegen(
                                "`%` is only defined for terah".into(),
                            ));
                        }
                        Ok(lt)
                    }
                    BinOp::Eq | BinOp::NotEq => {
                        if lt != rt {
                            return Err(Error::Codegen(format!(
                                "comparison type mismatch: {} vs {}",
                                type_name(lt),
                                type_name(rt)
                            )));
                        }
                        if lt == Type::Deshnash {
                            return Err(Error::Codegen(
                                "string equality is not yet supported".into(),
                            ));
                        }
                        Ok(Type::Bool)
                    }
                    BinOp::Lt | BinOp::Le | BinOp::Gt | BinOp::Ge => {
                        if lt != rt {
                            return Err(Error::Codegen(format!(
                                "comparison type mismatch: {} vs {}",
                                type_name(lt),
                                type_name(rt)
                            )));
                        }
                        if !matches!(lt, Type::Terah | Type::Daqosh) {
                            return Err(Error::Codegen(format!(
                                "ordering comparison needs numeric operands, got {}",
                                type_name(lt)
                            )));
                        }
                        Ok(Type::Bool)
                    }
                }
            }
            Expr::Unary { op, expr } => {
                self.write("(");
                self.write(match op {
                    UnOp::Neg => "-",
                    UnOp::Not => "!",
                });
                let t = self.emit_expr(expr)?;
                self.write(")");
                match op {
                    UnOp::Neg => {
                        if !matches!(t, Type::Terah | Type::Daqosh) {
                            return Err(Error::Codegen(format!(
                                "unary `-` requires numeric, got {}",
                                type_name(t)
                            )));
                        }
                        Ok(t)
                    }
                    UnOp::Not => {
                        if t != Type::Bool {
                            return Err(Error::Codegen(format!(
                                "unary `!` requires bool, got {}",
                                type_name(t)
                            )));
                        }
                        Ok(Type::Bool)
                    }
                }
            }
            Expr::LogicAnd(ops) => {
                self.write("(");
                for (i, op) in ops.iter().enumerate() {
                    if i > 0 {
                        self.write(" && ");
                    }
                    let t = self.emit_expr(op)?;
                    if t != Type::Bool {
                        return Err(Error::Codegen(format!(
                            "AND operand must be bool, got {}",
                            type_name(t)
                        )));
                    }
                }
                self.write(")");
                Ok(Type::Bool)
            }
            Expr::LogicOr(ops) => {
                self.write("(");
                for (i, op) in ops.iter().enumerate() {
                    if i > 0 {
                        self.write(" || ");
                    }
                    let t = self.emit_expr(op)?;
                    if t != Type::Bool {
                        return Err(Error::Codegen(format!(
                            "OR operand must be bool, got {}",
                            type_name(t)
                        )));
                    }
                }
                self.write(")");
                Ok(Type::Bool)
            }
            Expr::Call { callee, args } => {
                let sig = self
                    .functions
                    .get(callee)
                    .cloned()
                    .ok_or_else(|| Error::Codegen(format!("call to undefined function `{}`", callee)))?;
                if sig.params.len() != args.len() {
                    return Err(Error::Codegen(format!(
                        "function `{}` expects {} args, got {}",
                        callee,
                        sig.params.len(),
                        args.len()
                    )));
                }
                self.write(callee);
                self.write("(");
                for (i, (arg, expected)) in args.iter().zip(sig.params.iter()).enumerate() {
                    if i > 0 {
                        self.write(", ");
                    }
                    let at = self.emit_expr(arg)?;
                    if at != *expected {
                        return Err(Error::Codegen(format!(
                            "argument {} of `{}`: expected {}, got {}",
                            i + 1,
                            callee,
                            type_name(*expected),
                            type_name(at)
                        )));
                    }
                }
                self.write(")");
                sig.return_type.ok_or_else(|| {
                    Error::Codegen(format!(
                        "function `{}` returns no value but its result is used",
                        callee
                    ))
                })
            }
        }
    }

    fn emit_string_expr(&mut self, parts: &[StringPart]) -> Result<()> {
        // Fast path: no interpolations → single literal.
        let has_interp = parts
            .iter()
            .any(|p| matches!(p, StringPart::Interpolation(_)));
        if !has_interp {
            let combined: String = parts
                .iter()
                .map(|p| match p {
                    StringPart::Literal(s) => s.as_str(),
                    _ => unreachable!(),
                })
                .collect();
            self.write(&format!("MOTT_STR_LIT({})", c_string_literal(&combined)));
            return Ok(());
        }

        // Interpolated: build an array of mott_str parts and hand to runtime.
        // We use a compound literal — `mott_str_build((mott_str[]){...}, n)`.
        self.write("mott_str_build((mott_str[]){ ");
        for (i, part) in parts.iter().enumerate() {
            if i > 0 {
                self.write(", ");
            }
            match part {
                StringPart::Literal(s) => {
                    self.write(&format!("MOTT_STR_LIT({})", c_string_literal(s)));
                }
                StringPart::Interpolation(id) => {
                    let ty = self.lookup(id).ok_or_else(|| {
                        Error::Codegen(format!(
                            "undefined variable `{}` in string interpolation",
                            id
                        ))
                    })?;
                    match ty {
                        Type::Deshnash => self.write(id),
                        Type::Terah => self.write(&format!("mott_str_from_terah({})", id)),
                        Type::Daqosh => self.write(&format!("mott_str_from_daqosh({})", id)),
                        Type::Bool => self.write(&format!("mott_str_from_bool({})", id)),
                    }
                }
            }
        }
        self.write(&format!(" }}, {})", parts.len()));
        Ok(())
    }

    /// Read-only type inference used where we need to know the type without
    /// emitting (e.g. picking the right `yazde_*` helper before emitting args).
    fn infer(&self, e: &Expr) -> Result<Type> {
        match e {
            Expr::Integer(_) => Ok(Type::Terah),
            Expr::Float(_) => Ok(Type::Daqosh),
            Expr::Bool(_) => Ok(Type::Bool),
            Expr::String(_) => Ok(Type::Deshnash),
            Expr::Ident(name) => self
                .lookup(name)
                .ok_or_else(|| Error::Codegen(format!("use of undefined variable `{}`", name))),
            Expr::Binary { op, left, .. } => match op {
                BinOp::Eq | BinOp::NotEq | BinOp::Lt | BinOp::Le | BinOp::Gt | BinOp::Ge => {
                    Ok(Type::Bool)
                }
                _ => self.infer(left),
            },
            Expr::Unary { op, expr } => match op {
                UnOp::Not => Ok(Type::Bool),
                UnOp::Neg => self.infer(expr),
            },
            Expr::LogicAnd(_) | Expr::LogicOr(_) => Ok(Type::Bool),
            Expr::Call { callee, .. } => {
                let sig = self.functions.get(callee).ok_or_else(|| {
                    Error::Codegen(format!("call to undefined function `{}`", callee))
                })?;
                sig.return_type.ok_or_else(|| {
                    Error::Codegen(format!(
                        "function `{}` returns no value but its result is used",
                        callee
                    ))
                })
            }
        }
    }

    // --- scope management ---
    fn push_scope(&mut self) {
        self.scopes.push(HashMap::new());
    }
    fn pop_scope(&mut self) {
        self.scopes.pop();
    }
    fn declare(&mut self, name: &str, ty: Type) {
        self.scopes
            .last_mut()
            .expect("no active scope")
            .insert(name.to_string(), ty);
    }
    fn lookup(&self, name: &str) -> Option<Type> {
        for scope in self.scopes.iter().rev() {
            if let Some(t) = scope.get(name) {
                return Some(*t);
            }
        }
        None
    }

    // --- output helpers ---
    fn write(&mut self, s: &str) {
        self.out.push_str(s);
    }
    fn writeln(&mut self, s: &str) {
        self.out.push_str(s);
        self.out.push('\n');
    }
    fn write_indent(&mut self) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
    }
}

/// If `b` is a single-stmt block containing only an `If`, return its pieces.
/// This is the shape the parser produces for `khi nagah sanna` and lets the
/// backend re-emit `else if` instead of `else { if ... }`.
fn as_chained_if(b: &Block) -> Option<(&Expr, &Block, Option<&Block>)> {
    if b.stmts.len() != 1 {
        return None;
    }
    match &b.stmts[0] {
        Stmt::If {
            cond,
            then_block,
            else_block,
        } => Some((cond, then_block, else_block.as_ref())),
        _ => None,
    }
}

fn type_to_c(t: Type) -> &'static str {
    match t {
        Type::Terah => "int64_t",
        Type::Daqosh => "double",
        Type::Bool => "bool",
        Type::Deshnash => "mott_str",
    }
}

fn type_name(t: Type) -> &'static str {
    match t {
        Type::Terah => "terah",
        Type::Daqosh => "daqosh",
        Type::Bool => "bool",
        Type::Deshnash => "deshnash",
    }
}

fn bin_op_str(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => " + ",
        BinOp::Sub => " - ",
        BinOp::Mul => " * ",
        BinOp::Div => " / ",
        BinOp::Mod => " % ",
        BinOp::Eq => " == ",
        BinOp::NotEq => " != ",
        BinOp::Lt => " < ",
        BinOp::Le => " <= ",
        BinOp::Gt => " > ",
        BinOp::Ge => " >= ",
    }
}

/// Render `s` as a C double-quoted string literal. UTF-8 bytes outside
/// printable ASCII are emitted as `\xNN`, which works because mott source
/// is UTF-8 and we never split a multibyte sequence.
fn c_string_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for b in s.bytes() {
        match b {
            b'\\' => out.push_str("\\\\"),
            b'"' => out.push_str("\\\""),
            b'\n' => out.push_str("\\n"),
            b'\t' => out.push_str("\\t"),
            b'\r' => out.push_str("\\r"),
            0x20..=0x7e => out.push(b as char),
            _ => {
                // Hex-escape followed by a string-break prevents the next ASCII
                // digit from being absorbed into the \x escape.
                let _ = write!(out, "\\x{:02x}\"\"", b);
            }
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn compile(src: &str) -> Result<String> {
        let tokens = Lexer::new(src).tokenize().expect("lex");
        let program = Parser::new(tokens).parse().expect("parse");
        CBackend.emit(&program)
    }

    fn compile_ok(src: &str) -> String {
        compile(src).expect("codegen should succeed")
    }

    #[test]
    fn hello_world_produces_main() {
        let c = compile_ok("fnc kort() { yazde(\"Salam\"); }");
        assert!(c.contains("int main(void)"), "got:\n{}", c);
        assert!(c.contains("mott_yazde_deshnash"), "got:\n{}", c);
        assert!(c.contains("MOTT_STR_LIT(\"Salam\")"), "got:\n{}", c);
        assert!(c.contains("return 0;"), "got:\n{}", c);
    }

    #[test]
    fn int_let_and_arithmetic() {
        let c = compile_ok("fnc kort() { xilit x = 5; xilit y: terah = x + 3; yazde(y); }");
        assert!(c.contains("int64_t x ="));
        assert!(c.contains("int64_t y ="));
        assert!(c.contains("mott_yazde_terah(y)"));
    }

    #[test]
    fn interpolation_emits_str_build() {
        let c = compile_ok("fnc kort() { xilit x = 5; yazde(\"x = {x}\"); }");
        assert!(c.contains("mott_str_build"), "got:\n{}", c);
        assert!(c.contains("mott_str_from_terah(x)"), "got:\n{}", c);
        assert!(c.contains("MOTT_STR_LIT(\"x = \")"), "got:\n{}", c);
    }

    #[test]
    fn if_else_and_while() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit i: terah = 0;
    cqachunna (i < 3) {
        nagah sanna (i == 1) {
            yazde("one");
        } khi {
            yazde("other");
        }
        i = i + 1;
    }
}
"#,
        );
        assert!(c.contains("while ("));
        assert!(c.contains("if ("));
        assert!(c.contains("} else {"));
    }

    #[test]
    fn khi_nagah_sanna_emits_else_if() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit x: terah = 1;
    nagah sanna (x == 1) {
        yazde("one");
    } khi nagah sanna (x == 2) {
        yazde("two");
    } khi nagah sanna (x == 3) {
        yazde("three");
    } khi {
        yazde("other");
    }
}
"#,
        );
        // Should emit idiomatic `else if` — not nested `else { if ... }`.
        assert!(
            c.contains("} else if ("),
            "expected idiomatic `else if`, got:\n{}",
            c
        );
        // Exactly one final `} else {` for the terminal branch.
        assert_eq!(c.matches("} else {").count(), 1, "got:\n{}", c);
        // No spurious nested brace-wrapped if.
        assert!(
            !c.contains("} else {\n            if ("),
            "chain should not produce nested blocks, got:\n{}",
            c
        );
    }

    #[test]
    fn logic_and_becomes_cc_and() {
        let c = compile_ok(
            "fnc kort() { xilit x: terah = 5; nagah sanna (x > 0 a, x < 10 a) { yazde(\"ok\"); } }",
        );
        assert!(c.contains(" && "), "got:\n{}", c);
    }

    #[test]
    fn logic_or_becomes_cc_or() {
        let c = compile_ok(
            "fnc kort() { xilit x: terah = 5; nagah sanna (x < 0 ya x > 10) { yazde(\"out\"); } }",
        );
        assert!(c.contains(" || "), "got:\n{}", c);
    }

    #[test]
    fn function_with_params_emits_forward_decl() {
        let c = compile_ok(
            r#"
fnc add(x: terah, y: terah) -> terah {
    yuxadalo x + y;
}
fnc kort() {
    xilit z = add(2, 3);
    yazde(z);
}
"#,
        );
        assert!(c.contains("int64_t add(int64_t x, int64_t y);"), "got:\n{}", c);
        assert!(c.contains("int64_t add(int64_t x, int64_t y) {"), "got:\n{}", c);
        assert!(c.contains("add(((int64_t)2LL), ((int64_t)3LL))"), "got:\n{}", c);
    }

    #[test]
    fn type_mismatch_in_let_errors() {
        let err = compile("fnc kort() { xilit x: terah = baqderg; }").unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("type mismatch"), "got: {}", msg);
    }

    #[test]
    fn undefined_variable_errors() {
        let err = compile("fnc kort() { yazde(nope); }").unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("undefined variable"), "got: {}", msg);
    }

    #[test]
    fn kort_with_params_is_rejected() {
        let err = compile("fnc kort(x: terah) { yazde(x); }").unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("kort"), "got: {}", msg);
    }

    #[test]
    fn non_bool_condition_is_rejected() {
        let err = compile("fnc kort() { xilit x = 1; nagah sanna (x) { yazde(\"hi\"); } }")
            .unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("must be bool"), "got: {}", msg);
    }

    #[test]
    fn sac_and_khida_emit_break_continue() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit i: terah = 0;
    cqachunna (i < 10) {
        nagah sanna (i == 5) {
            sac;
        }
        i = i + 1;
        khida;
    }
}
"#,
        );
        assert!(c.contains("break;"), "got:\n{}", c);
        assert!(c.contains("continue;"), "got:\n{}", c);
    }

    #[test]
    fn sac_outside_loop_errors() {
        let err = compile("fnc kort() { sac; }").unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("outside of"), "got: {}", msg);
    }

    #[test]
    fn khida_outside_loop_errors() {
        let err = compile("fnc kort() { khida; }").unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("outside of"), "got: {}", msg);
    }

    #[test]
    fn sac_inside_if_inside_loop_is_ok() {
        // An if nested in a loop must still allow `sac`.
        let c = compile_ok(
            r#"
fnc kort() {
    xilit i: terah = 0;
    cqachunna (i < 10) {
        nagah sanna (i > 3) {
            sac;
        }
        i = i + 1;
    }
}
"#,
        );
        assert!(c.contains("break;"));
    }

    #[test]
    fn sac_in_separate_function_is_scoped() {
        // `cqachunna` in helper shouldn't let `sac` escape into `kort`.
        let err = compile(
            r#"
fnc helper() {
    cqachunna (baqderg) { sac; }
}
fnc kort() {
    sac;
}
"#,
        )
        .unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("outside of"), "got: {}", msg);
    }
}
