//! C backend: walks the Mott AST and emits portable C11.
//!
//! Notes on the runtime contract (see `runtime/mott_rt.h`):
//! - `terah` maps to `int64_t`, `daqosh` to `double`, `bool` to `bool`,
//!   `deshnash` to `mott_str` (struct with `data` + `len`).
//! - String interpolation is lowered to a `mott_str_build(parts, n)` call
//!   that concatenates into a heap-allocated (leaked) buffer.
//! - `yazde` is dispatched at codegen time to the per-type runtime helper
//!   (`mott_yazde_terah`, etc.) — the language surface has one `yazde` but
//!   C needs a monomorphic function.
//!
//! Type handling is deliberately minimal here (MVP): we do inline inference
//! during emission so a `xilit x = 5;` doesn't require a separate sema pass.
//! v0.2 will lift this into a real checker.

use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

use crate::ast::{BinOp, Block, Expr, Function, Item, IterSource, Program, Stmt, Type, UnOp};
use crate::codegen::Backend;
use crate::error::{Error, Result};
use crate::token::StringPart;

pub struct CBackend;

impl Backend for CBackend {
    fn name(&self) -> &'static str {
        "c"
    }

    fn emit(&self, program: &Program) -> Result<String> {
        let mut e = Emitter::new(program)?;
        e.emit_program(program)?;
        Ok(e.out)
    }
}

#[derive(Debug, Clone)]
struct FuncSig {
    params: Vec<Type>,
    return_type: Option<Type>,
}

struct Emitter {
    out: String,
    indent: usize,
    scopes: Vec<HashMap<String, Type>>,
    functions: HashMap<String, FuncSig>,
    /// Depth of enclosing `cqachunna` loops. Used to validate that `sac` and
    /// `khida` only appear inside a loop — outside, they'd generate C that
    /// clang would reject, but we want to catch it with a mott-level error.
    loop_depth: usize,
    /// Names of the current function's parameters. push/pop are rejected
    /// on these because Mott arrays are value types sharing a buffer — a
    /// realloc in push would invalidate the caller's pointer. Resetting on
    /// every function entry (parameters don't leak across functions).
    current_params: HashSet<String>,
}

impl Emitter {
    fn new(program: &Program) -> Result<Self> {
        let mut functions = HashMap::new();
        for item in &program.items {
            let Item::Function(f) = item;
            let sig = FuncSig {
                params: f.params.iter().map(|p| p.ty.clone()).collect(),
                return_type: f.return_type.clone(),
            };
            if functions.insert(f.name.clone(), sig).is_some() {
                return Err(Error::Codegen(format!(
                    "duplicate function `{}`",
                    f.name
                )));
            }
        }
        Ok(Self {
            out: String::new(),
            indent: 0,
            scopes: Vec::new(),
            functions,
            loop_depth: 0,
            current_params: HashSet::new(),
        })
    }

    fn emit_program(&mut self, program: &Program) -> Result<()> {
        self.write_prelude();

        // Forward-declare every non-entry function so call-before-define works.
        let mut has_decls = false;
        for item in &program.items {
            let Item::Function(f) = item;
            if f.name == "kort" {
                continue;
            }
            self.emit_function_signature(f);
            self.writeln(";");
            has_decls = true;
        }
        if has_decls {
            self.writeln("");
        }

        for item in &program.items {
            let Item::Function(f) = item;
            self.emit_function(f)?;
            self.writeln("");
        }
        Ok(())
    }

    fn write_prelude(&mut self) {
        self.writeln("/* Generated by mott compiler v0.1 — do not edit. */");
        self.writeln("#include <stdbool.h>");
        self.writeln("#include <stdint.h>");
        self.writeln("#include \"mott_rt.h\"");
        self.writeln("");
    }

    fn emit_function_signature(&mut self, f: &Function) {
        let ret = match &f.return_type {
            Some(t) => type_to_c(t),
            None => "void".into(),
        };
        self.write(&format!("{} {}(", ret, f.name));
        if f.params.is_empty() {
            self.write("void");
        } else {
            for (i, p) in f.params.iter().enumerate() {
                if i > 0 {
                    self.write(", ");
                }
                self.write(&format!("{} {}", type_to_c(&p.ty), p.name));
            }
        }
        self.write(")");
    }

    fn emit_function(&mut self, f: &Function) -> Result<()> {
        if f.name == "kort" {
            if !f.params.is_empty() {
                return Err(Error::Codegen(
                    "entry function `kort` must not take parameters".into(),
                ));
            }
            if f.return_type.is_some() {
                return Err(Error::Codegen(
                    "entry function `kort` must not declare a return type".into(),
                ));
            }
            self.write("int main(void)");
        } else {
            self.emit_function_signature(f);
        }
        self.writeln(" {");
        self.indent += 1;
        self.push_scope();
        self.current_params = f.params.iter().map(|p| p.name.clone()).collect();
        for p in &f.params {
            self.declare(&p.name, p.ty.clone());
        }
        for s in &f.body.stmts {
            self.emit_stmt(s)?;
        }
        if f.name == "kort" {
            self.write_indent();
            self.writeln("return 0;");
        }
        self.pop_scope();
        self.current_params.clear();
        self.indent -= 1;
        self.writeln("}");
        Ok(())
    }

    /// Emit a `yallalc var chu iter { body }` loop. For arrays we iterate by
    /// index and bind `var` to the element; for ranges we emit a plain
    /// counting loop.
    fn emit_for_each(
        &mut self,
        var: &str,
        iter: &IterSource,
        body: &Block,
    ) -> Result<()> {
        match iter {
            IterSource::Range { start, end } => {
                self.write_indent();
                self.write(&format!("for (int64_t {} = ", var));
                let st = self.emit_expr(start)?;
                if st != Type::Terah {
                    return Err(Error::Codegen(format!(
                        "range start must be terah, got {}",
                        type_name(&st)
                    )));
                }
                self.write(&format!("; {} < ", var));
                let et = self.emit_expr(end)?;
                if et != Type::Terah {
                    return Err(Error::Codegen(format!(
                        "range end must be terah, got {}",
                        type_name(&et)
                    )));
                }
                self.write(&format!("; {}++)", var));
                self.loop_depth += 1;
                self.push_scope();
                self.declare(var, Type::Terah);
                let r = self.emit_block_body(body);
                self.pop_scope();
                self.loop_depth -= 1;
                r?;
                self.writeln("");
            }
            IterSource::Array(arr_expr) => {
                // Emit: { TYPE __arr = <arr>; for (size_t __i = 0; __i < __arr.len; __i++) { ELEM var = __arr.data[__i]; body } }
                // The outer block scopes the temp names. We give `var` the
                // element type in our scope tracker so the body sees it
                // correctly.
                let arr_ty = self.infer(arr_expr)?;
                let elem_ty = match &arr_ty {
                    Type::Array(inner) => (**inner).clone(),
                    other => {
                        return Err(Error::Codegen(format!(
                            "`yallalc ... chu` needs an array, got {}",
                            type_name(other)
                        )));
                    }
                };
                self.write_indent();
                self.writeln("{");
                self.indent += 1;
                // temp for the array so we only evaluate it once
                self.write_indent();
                self.write(&format!("{} __mott_arr = ", type_to_c(&arr_ty)));
                self.emit_expr(arr_expr)?;
                self.writeln(";");
                self.write_indent();
                self.write(
                    "for (size_t __mott_i = 0; __mott_i < __mott_arr.len; __mott_i++)",
                );
                self.writeln(" {");
                self.indent += 1;
                self.write_indent();
                self.writeln(&format!(
                    "{} {} = __mott_arr.data[__mott_i];",
                    type_to_c(&elem_ty),
                    var
                ));
                self.loop_depth += 1;
                self.push_scope();
                self.declare(var, elem_ty);
                let body_result: Result<()> = (|| {
                    for s in &body.stmts {
                        self.emit_stmt(s)?;
                    }
                    Ok(())
                })();
                self.pop_scope();
                self.loop_depth -= 1;
                body_result?;
                self.indent -= 1;
                self.write_indent();
                self.writeln("}");
                self.indent -= 1;
                self.write_indent();
                self.writeln("}");
            }
        }
        Ok(())
    }

    /// Emit just the statements of a block, without opening/closing braces
    /// or pushing a scope. Used by for-each where the caller manages
    /// bracing and scoping itself.
    fn emit_block_body(&mut self, b: &Block) -> Result<()> {
        self.writeln(" {");
        self.indent += 1;
        self.push_scope();
        for s in &b.stmts {
            self.emit_stmt(s)?;
        }
        self.pop_scope();
        self.indent -= 1;
        self.write_indent();
        self.write("}");
        Ok(())
    }

    /// Emit `callee(arg1, arg2, ...)` with full arity + type checking.
    /// Callers that need the return type handle it separately; this helper
    /// only produces the call expression itself so it can be reused by both
    /// `emit_expr` (value context) and ExprStmt (discarded-result context).
    fn emit_call(&mut self, callee: &str, args: &[Expr], sig: &FuncSig) -> Result<()> {
        if sig.params.len() != args.len() {
            return Err(Error::Codegen(format!(
                "function `{}` expects {} args, got {}",
                callee,
                sig.params.len(),
                args.len()
            )));
        }
        self.write(callee);
        self.write("(");
        for (i, (arg, expected)) in args.iter().zip(sig.params.iter()).enumerate() {
            if i > 0 {
                self.write(", ");
            }
            let at = self.emit_expr(arg)?;
            if at != *expected {
                return Err(Error::Codegen(format!(
                    "argument {} of `{}`: expected {}, got {}",
                    i + 1,
                    callee,
                    type_name(expected),
                    type_name(&at)
                )));
            }
        }
        self.write(")");
        Ok(())
    }

    /// Emit `if (cond) {...} [else ...]` without a leading indent, collapsing
    /// parser-desugared `khi nagah sanna` chains back into idiomatic C
    /// `else if`. Parser wraps each chained condition in a single-stmt block
    /// — we detect that shape and recurse instead of nesting braces.
    fn emit_if_chain(
        &mut self,
        cond: &Expr,
        then_block: &Block,
        else_block: Option<&Block>,
    ) -> Result<()> {
        self.write("if (");
        let ct = self.emit_expr(cond)?;
        if ct != Type::Bool {
            return Err(Error::Codegen(format!(
                "`nagah sanna` condition must be bool, got {}",
                type_name(&ct)
            )));
        }
        self.write(")");
        self.emit_block_inline(then_block)?;
        if let Some(eb) = else_block {
            if let Some((c2, t2, e2)) = as_chained_if(eb) {
                self.write(" else ");
                self.emit_if_chain(c2, t2, e2)?;
            } else {
                self.write(" else");
                self.emit_block_inline(eb)?;
            }
        }
        Ok(())
    }

    /// Emit `{ ... }` for a control-flow body. Assumes the caller already
    /// wrote everything up to (but not including) the opening brace.
    fn emit_block_inline(&mut self, b: &Block) -> Result<()> {
        self.writeln(" {");
        self.indent += 1;
        self.push_scope();
        for s in &b.stmts {
            self.emit_stmt(s)?;
        }
        self.pop_scope();
        self.indent -= 1;
        self.write_indent();
        self.write("}");
        Ok(())
    }

    fn emit_stmt(&mut self, s: &Stmt) -> Result<()> {
        match s {
            Stmt::Let { name, ty, value } => {
                self.write_indent();
                let actual_ty = match ty {
                    Some(t) => t.clone(),
                    None => self.infer(value)?,
                };
                if self.scopes.last().unwrap().contains_key(name) {
                    return Err(Error::Codegen(format!(
                        "variable `{}` already declared in this scope",
                        name
                    )));
                }
                self.write(&format!("{} {} = ", type_to_c(&actual_ty), name));
                // Empty array literal `[]` can only be typed from the
                // annotation — infer() / emit_expr() alone would fail on
                // element-type inference. Handle it here so it Just Works
                // in the natural `xilit nums: [terah] = []` case.
                let val_ty = if let (Expr::ArrayLit(elems), Type::Array(elem_ty)) =
                    (value, &actual_ty)
                {
                    if elems.is_empty() {
                        let ctor = array_ctor_name(elem_ty);
                        self.write(&format!("{}(0, NULL)", ctor));
                        actual_ty.clone()
                    } else {
                        self.emit_expr(value)?
                    }
                } else {
                    self.emit_expr(value)?
                };
                if ty.is_some() && val_ty != actual_ty {
                    return Err(Error::Codegen(format!(
                        "type mismatch: `{}` declared as {} but initializer is {}",
                        name,
                        type_name(&actual_ty),
                        type_name(&val_ty)
                    )));
                }
                self.writeln(";");
                self.declare(name, actual_ty);
            }
            Stmt::Assign { name, value } => {
                let target_ty = self.lookup(name).ok_or_else(|| {
                    Error::Codegen(format!("assignment to undefined variable `{}`", name))
                })?;
                self.write_indent();
                self.write(&format!("{} = ", name));
                let val_ty = self.emit_expr(value)?;
                if val_ty != target_ty {
                    return Err(Error::Codegen(format!(
                        "type mismatch: `{}` is {} but value is {}",
                        name,
                        type_name(&target_ty),
                        type_name(&val_ty)
                    )));
                }
                self.writeln(";");
            }
            Stmt::If {
                cond,
                then_block,
                else_block,
            } => {
                self.write_indent();
                self.emit_if_chain(cond, then_block, else_block.as_ref())?;
                self.writeln("");
            }
            Stmt::While { cond, body } => {
                self.write_indent();
                self.write("while (");
                let ct = self.emit_expr(cond)?;
                if ct != Type::Bool {
                    return Err(Error::Codegen(format!(
                        "`cqachunna` condition must be bool, got {}",
                        type_name(&ct)
                    )));
                }
                self.write(")");
                self.loop_depth += 1;
                let body_result = self.emit_block_inline(body);
                self.loop_depth -= 1;
                body_result?;
                self.writeln("");
            }
            Stmt::Break => {
                if self.loop_depth == 0 {
                    return Err(Error::Codegen(
                        "`sac` outside of `cqachunna` loop".into(),
                    ));
                }
                self.write_indent();
                self.writeln("break;");
            }
            Stmt::Continue => {
                if self.loop_depth == 0 {
                    return Err(Error::Codegen(
                        "`khida` outside of `cqachunna` loop".into(),
                    ));
                }
                self.write_indent();
                self.writeln("continue;");
            }
            Stmt::Return(e) => {
                self.write_indent();
                match e {
                    Some(expr) => {
                        self.write("return ");
                        self.emit_expr(expr)?;
                        self.writeln(";");
                    }
                    None => self.writeln("return;"),
                }
            }
            Stmt::Print(e) => {
                let ty = self.infer(e)?;
                let helper = match ty {
                    Type::Terah => "mott_yazde_terah",
                    Type::Daqosh => "mott_yazde_daqosh",
                    Type::Bool => "mott_yazde_bool",
                    Type::Deshnash => "mott_yazde_deshnash",
                    Type::Array(_) => {
                        return Err(Error::Codegen(
                            "can't print arrays directly yet — iterate \
                             with `yallalc` and print each element"
                                .into(),
                        ));
                    }
                };
                self.write_indent();
                self.write(&format!("{}(", helper));
                self.emit_expr(e)?;
                self.writeln(");");
            }
            Stmt::ExprStmt(e) => {
                self.write_indent();
                // Call to a void function is valid as a bare statement
                // (result discarded) even though `emit_expr` refuses to
                // produce one in a value-needing context. Handle it inline.
                if let Expr::Call { callee, args } = e {
                    if let Some(sig) = self.functions.get(callee).cloned() {
                        if sig.return_type.is_none() {
                            self.emit_call(callee, args, &sig)?;
                            self.writeln(";");
                            return Ok(());
                        }
                    }
                }
                self.emit_expr(e)?;
                self.writeln(";");
            }
            Stmt::IndexAssign { name, index, value } => {
                // Check target is an array; element type must match value.
                let arr_ty = self.lookup(name).ok_or_else(|| {
                    Error::Codegen(format!(
                        "assignment to undefined variable `{}`",
                        name
                    ))
                })?;
                let elem_ty = match &arr_ty {
                    Type::Array(inner) => (**inner).clone(),
                    other => {
                        return Err(Error::Codegen(format!(
                            "`{}` is {}, can't index-assign",
                            name,
                            type_name(other)
                        )));
                    }
                };
                self.write_indent();
                self.write(&format!("{}.data[", name));
                let idx_ty = self.emit_expr(index)?;
                if idx_ty != Type::Terah {
                    return Err(Error::Codegen(format!(
                        "array index must be terah, got {}",
                        type_name(&idx_ty)
                    )));
                }
                self.write("] = ");
                let val_ty = self.emit_expr(value)?;
                if val_ty != elem_ty {
                    return Err(Error::Codegen(format!(
                        "element type mismatch: array is [{}] but value is {}",
                        type_name(&elem_ty),
                        type_name(&val_ty)
                    )));
                }
                self.writeln(";");
            }
            Stmt::ForEach { var, iter, body } => {
                self.emit_for_each(var, iter, body)?;
            }
            Stmt::Push { name, value } => {
                let arr_ty = self.lookup(name).ok_or_else(|| {
                    Error::Codegen(format!("push on undefined variable `{}`", name))
                })?;
                let elem_ty = match &arr_ty {
                    Type::Array(inner) => (**inner).clone(),
                    other => {
                        return Err(Error::Codegen(format!(
                            "`push` needs an array, but `{}` is {}",
                            name,
                            type_name(other)
                        )));
                    }
                };
                // Aliasing footgun: Mott passes arrays by value (struct
                // copy) but data pointer is shared. push can realloc,
                // invalidating the caller's view. Reject on params until
                // we have references.
                if self.current_params.contains(name) {
                    return Err(Error::Codegen(format!(
                        "cannot push to `{}`: it's a function parameter, \
                         and mott doesn't have references yet — push/pop \
                         only work on locals",
                        name
                    )));
                }
                let push_fn = array_push_name(&elem_ty);
                self.write_indent();
                self.write(&format!("{}(&{}, ", push_fn, name));
                let val_ty = self.emit_expr(value)?;
                if val_ty != elem_ty {
                    return Err(Error::Codegen(format!(
                        "push type mismatch: `{}` holds {}, got {}",
                        name,
                        type_name(&elem_ty),
                        type_name(&val_ty)
                    )));
                }
                self.writeln(");");
            }
        }
        Ok(())
    }

    /// Emit an expression and return its type. Always wraps in parens so
    /// precedence never bites us — the C compiler will clean it up.
    fn emit_expr(&mut self, e: &Expr) -> Result<Type> {
        match e {
            Expr::Integer(n) => {
                // INT64_MIN cannot be written as a single negated literal in C.
                if *n == i64::MIN {
                    self.write("((int64_t)(-9223372036854775807LL - 1))");
                } else {
                    self.write(&format!("((int64_t){}LL)", n));
                }
                Ok(Type::Terah)
            }
            Expr::Float(f) => {
                // {:?} preserves enough precision to round-trip.
                // Force a decimal point so the literal is always interpreted as double.
                let s = format!("{:?}", f);
                let s = if s.contains('.') || s.contains('e') || s.contains("inf") || s.contains("nan") {
                    s
                } else {
                    format!("{}.0", s)
                };
                self.write(&s);
                Ok(Type::Daqosh)
            }
            Expr::Bool(b) => {
                self.write(if *b { "true" } else { "false" });
                Ok(Type::Bool)
            }
            Expr::Ident(name) => {
                let ty = self.lookup(name).ok_or_else(|| {
                    Error::Codegen(format!("use of undefined variable `{}`", name))
                })?;
                self.write(name);
                Ok(ty)
            }
            Expr::String(parts) => {
                self.emit_string_expr(parts)?;
                Ok(Type::Deshnash)
            }
            Expr::Binary { op, left, right } => {
                // String equality can't use C's `==` on mott_str structs —
                // that would just compare data pointers. Pre-check types and
                // lower to a runtime call that does byte-level comparison.
                if matches!(op, BinOp::Eq | BinOp::NotEq) {
                    let lt_pre = self.infer(left)?;
                    let rt_pre = self.infer(right)?;
                    if lt_pre == Type::Deshnash || rt_pre == Type::Deshnash {
                        if lt_pre != rt_pre {
                            return Err(Error::Codegen(format!(
                                "comparison type mismatch: {} vs {}",
                                type_name(&lt_pre),
                                type_name(&rt_pre)
                            )));
                        }
                        let negate = matches!(op, BinOp::NotEq);
                        if negate {
                            self.write("(!mott_str_eq(");
                        } else {
                            self.write("mott_str_eq(");
                        }
                        self.emit_expr(left)?;
                        self.write(", ");
                        self.emit_expr(right)?;
                        self.write(if negate { "))" } else { ")" });
                        return Ok(Type::Bool);
                    }
                }

                self.write("(");
                let lt = self.emit_expr(left)?;
                self.write(bin_op_str(*op));
                let rt = self.emit_expr(right)?;
                self.write(")");
                match op {
                    BinOp::Add | BinOp::Sub | BinOp::Mul | BinOp::Div | BinOp::Mod => {
                        if lt != rt {
                            return Err(Error::Codegen(format!(
                                "arithmetic type mismatch: {} vs {}",
                                type_name(&lt),
                                type_name(&rt)
                            )));
                        }
                        if !matches!(lt, Type::Terah | Type::Daqosh) {
                            return Err(Error::Codegen(format!(
                                "arithmetic on non-numeric type {}",
                                type_name(&lt)
                            )));
                        }
                        if matches!(op, BinOp::Mod) && lt != Type::Terah {
                            return Err(Error::Codegen(
                                "`%` is only defined for terah".into(),
                            ));
                        }
                        Ok(lt)
                    }
                    BinOp::Eq | BinOp::NotEq => {
                        // Deshnash case was handled above before entering the
                        // generic path. Any remaining mismatch is a type error.
                        if lt != rt {
                            return Err(Error::Codegen(format!(
                                "comparison type mismatch: {} vs {}",
                                type_name(&lt),
                                type_name(&rt)
                            )));
                        }
                        Ok(Type::Bool)
                    }
                    BinOp::Lt | BinOp::Le | BinOp::Gt | BinOp::Ge => {
                        if lt != rt {
                            return Err(Error::Codegen(format!(
                                "comparison type mismatch: {} vs {}",
                                type_name(&lt),
                                type_name(&rt)
                            )));
                        }
                        if !matches!(lt, Type::Terah | Type::Daqosh) {
                            return Err(Error::Codegen(format!(
                                "ordering comparison needs numeric operands, got {}",
                                type_name(&lt)
                            )));
                        }
                        Ok(Type::Bool)
                    }
                }
            }
            Expr::Unary { op, expr } => {
                self.write("(");
                self.write(match op {
                    UnOp::Neg => "-",
                    UnOp::Not => "!",
                });
                let t = self.emit_expr(expr)?;
                self.write(")");
                match op {
                    UnOp::Neg => {
                        if !matches!(t, Type::Terah | Type::Daqosh) {
                            return Err(Error::Codegen(format!(
                                "unary `-` requires numeric, got {}",
                                type_name(&t)
                            )));
                        }
                        Ok(t)
                    }
                    UnOp::Not => {
                        if t != Type::Bool {
                            return Err(Error::Codegen(format!(
                                "unary `!` requires bool, got {}",
                                type_name(&t)
                            )));
                        }
                        Ok(Type::Bool)
                    }
                }
            }
            Expr::LogicAnd(ops) => {
                self.write("(");
                for (i, op) in ops.iter().enumerate() {
                    if i > 0 {
                        self.write(" && ");
                    }
                    let t = self.emit_expr(op)?;
                    if t != Type::Bool {
                        return Err(Error::Codegen(format!(
                            "AND operand must be bool, got {}",
                            type_name(&t)
                        )));
                    }
                }
                self.write(")");
                Ok(Type::Bool)
            }
            Expr::LogicOr(ops) => {
                self.write("(");
                for (i, op) in ops.iter().enumerate() {
                    if i > 0 {
                        self.write(" || ");
                    }
                    let t = self.emit_expr(op)?;
                    if t != Type::Bool {
                        return Err(Error::Codegen(format!(
                            "OR operand must be bool, got {}",
                            type_name(&t)
                        )));
                    }
                }
                self.write(")");
                Ok(Type::Bool)
            }
            Expr::Call { callee, args } => {
                let sig = self
                    .functions
                    .get(callee)
                    .cloned()
                    .ok_or_else(|| Error::Codegen(format!("call to undefined function `{}`", callee)))?;
                self.emit_call(callee, args, &sig)?;
                // In expression position, void calls have no usable value.
                // ExprStmt routes around this via its own path.
                sig.return_type.ok_or_else(|| {
                    Error::Codegen(format!(
                        "function `{}` returns no value but its result is used",
                        callee
                    ))
                })
            }
            Expr::Input => {
                self.write("mott_input()");
                Ok(Type::Deshnash)
            }
            Expr::ArrayLit(elems) => {
                if elems.is_empty() {
                    // Empty literals are only valid when the context supplies
                    // the type — Stmt::Let handles that path directly. Hitting
                    // this here means someone wrote `[]` in a context where we
                    // can't infer it (a function arg, a `yazde(...)` target, etc).
                    return Err(Error::Codegen(
                        "empty array literal `[]` needs a type annotation; \
                         write `xilit nums: [terah] = []` or use `[1, 2, 3]`"
                            .into(),
                    ));
                }
                // Determine element type from the first element; all others
                // must match. Reject nested arrays for now.
                let first_ty = self.infer(&elems[0])?;
                if matches!(first_ty, Type::Array(_)) {
                    return Err(Error::Codegen(
                        "nested arrays aren't supported yet".into(),
                    ));
                }
                for (i, e) in elems.iter().enumerate().skip(1) {
                    let t = self.infer(e)?;
                    if t != first_ty {
                        return Err(Error::Codegen(format!(
                            "array literal element {}: expected {}, got {}",
                            i,
                            type_name(&first_ty),
                            type_name(&t)
                        )));
                    }
                }
                let elem_c = type_to_c(&first_ty);
                let ctor = array_ctor_name(&first_ty);
                self.write(&format!("{}({}, (", ctor, elems.len()));
                self.write(&format!("{}[]){{ ", elem_c));
                for (i, e) in elems.iter().enumerate() {
                    if i > 0 {
                        self.write(", ");
                    }
                    self.emit_expr(e)?;
                }
                self.write(" })");
                Ok(Type::Array(Box::new(first_ty)))
            }
            Expr::Index { target, index } => {
                let tgt_ty = self.infer(target)?;
                let elem_ty = match &tgt_ty {
                    Type::Array(inner) => (**inner).clone(),
                    other => {
                        return Err(Error::Codegen(format!(
                            "cannot index into non-array type {}",
                            type_name(other)
                        )));
                    }
                };
                self.write("(");
                self.emit_expr(target)?;
                self.write(".data[");
                let idx_ty = self.emit_expr(index)?;
                if idx_ty != Type::Terah {
                    return Err(Error::Codegen(format!(
                        "array index must be terah, got {}",
                        type_name(&idx_ty)
                    )));
                }
                self.write("])");
                Ok(elem_ty)
            }
            Expr::Baram(inner) => {
                let t = self.infer(inner)?;
                if !matches!(t, Type::Array(_) | Type::Deshnash) {
                    return Err(Error::Codegen(format!(
                        "`baram` needs an array or string, got {}",
                        type_name(&t)
                    )));
                }
                // Struct layout for both mott_arr_* and mott_str has `.len`
                // as the second field — one emission works for both. Cast
                // to int64_t because .len is size_t and Mott numbers are
                // all terah (int64).
                self.write("((int64_t)(");
                self.emit_expr(inner)?;
                self.write(".len))");
                Ok(Type::Terah)
            }
            Expr::ParseTerah(inner) => {
                let t = self.infer(inner)?;
                if t != Type::Deshnash {
                    return Err(Error::Codegen(format!(
                        "`parse_terah` needs a deshnash, got {}",
                        type_name(&t)
                    )));
                }
                self.write("mott_parse_terah(");
                self.emit_expr(inner)?;
                self.write(")");
                Ok(Type::Terah)
            }
            Expr::ParseDaqosh(inner) => {
                let t = self.infer(inner)?;
                if t != Type::Deshnash {
                    return Err(Error::Codegen(format!(
                        "`parse_daqosh` needs a deshnash, got {}",
                        type_name(&t)
                    )));
                }
                self.write("mott_parse_daqosh(");
                self.emit_expr(inner)?;
                self.write(")");
                Ok(Type::Daqosh)
            }
            Expr::ToTerah(inner) => {
                let t = self.infer(inner)?;
                if !matches!(t, Type::Terah | Type::Daqosh) {
                    return Err(Error::Codegen(format!(
                        "`to_terah` needs a numeric type (terah or daqosh), got {}",
                        type_name(&t)
                    )));
                }
                // C cast — truncates toward zero for floats. No runtime call.
                self.write("((int64_t)(");
                self.emit_expr(inner)?;
                self.write("))");
                Ok(Type::Terah)
            }
            Expr::ToDaqosh(inner) => {
                let t = self.infer(inner)?;
                if !matches!(t, Type::Terah | Type::Daqosh) {
                    return Err(Error::Codegen(format!(
                        "`to_daqosh` needs a numeric type (terah or daqosh), got {}",
                        type_name(&t)
                    )));
                }
                self.write("((double)(");
                self.emit_expr(inner)?;
                self.write("))");
                Ok(Type::Daqosh)
            }
            Expr::Pop(name) => {
                let arr_ty = self.lookup(name).ok_or_else(|| {
                    Error::Codegen(format!("pop on undefined variable `{}`", name))
                })?;
                let elem_ty = match &arr_ty {
                    Type::Array(inner) => (**inner).clone(),
                    other => {
                        return Err(Error::Codegen(format!(
                            "`pop` needs an array, but `{}` is {}",
                            name,
                            type_name(other)
                        )));
                    }
                };
                if self.current_params.contains(name) {
                    return Err(Error::Codegen(format!(
                        "cannot pop from `{}`: it's a function parameter \
                         (see push error message for why)",
                        name
                    )));
                }
                let pop_fn = array_pop_name(&elem_ty);
                self.write(&format!("{}(&{})", pop_fn, name));
                Ok(elem_ty)
            }
        }
    }

    fn emit_string_expr(&mut self, parts: &[StringPart]) -> Result<()> {
        // Fast path: no interpolations → single literal.
        let has_interp = parts
            .iter()
            .any(|p| matches!(p, StringPart::Interpolation(_)));
        if !has_interp {
            let combined: String = parts
                .iter()
                .map(|p| match p {
                    StringPart::Literal(s) => s.as_str(),
                    _ => unreachable!(),
                })
                .collect();
            self.write(&format!("MOTT_STR_LIT({})", c_string_literal(&combined)));
            return Ok(());
        }

        // Interpolated: build an array of mott_str parts and hand to runtime.
        // We use a compound literal — `mott_str_build((mott_str[]){...}, n)`.
        self.write("mott_str_build((mott_str[]){ ");
        for (i, part) in parts.iter().enumerate() {
            if i > 0 {
                self.write(", ");
            }
            match part {
                StringPart::Literal(s) => {
                    self.write(&format!("MOTT_STR_LIT({})", c_string_literal(s)));
                }
                StringPart::Interpolation(id) => {
                    let ty = self.lookup(id).ok_or_else(|| {
                        Error::Codegen(format!(
                            "undefined variable `{}` in string interpolation",
                            id
                        ))
                    })?;
                    match ty {
                        Type::Deshnash => self.write(id),
                        Type::Terah => self.write(&format!("mott_str_from_terah({})", id)),
                        Type::Daqosh => self.write(&format!("mott_str_from_daqosh({})", id)),
                        Type::Bool => self.write(&format!("mott_str_from_bool({})", id)),
                        Type::Array(_) => {
                            return Err(Error::Codegen(format!(
                                "cannot interpolate array `{}` into a string",
                                id
                            )));
                        }
                    }
                }
            }
        }
        self.write(&format!(" }}, {})", parts.len()));
        Ok(())
    }

    /// Read-only type inference used where we need to know the type without
    /// emitting (e.g. picking the right `yazde_*` helper before emitting args).
    fn infer(&self, e: &Expr) -> Result<Type> {
        match e {
            Expr::Integer(_) => Ok(Type::Terah),
            Expr::Float(_) => Ok(Type::Daqosh),
            Expr::Bool(_) => Ok(Type::Bool),
            Expr::String(_) => Ok(Type::Deshnash),
            Expr::Ident(name) => self
                .lookup(name)
                .ok_or_else(|| Error::Codegen(format!("use of undefined variable `{}`", name))),
            Expr::Binary { op, left, .. } => match op {
                BinOp::Eq | BinOp::NotEq | BinOp::Lt | BinOp::Le | BinOp::Gt | BinOp::Ge => {
                    Ok(Type::Bool)
                }
                _ => self.infer(left),
            },
            Expr::Unary { op, expr } => match op {
                UnOp::Not => Ok(Type::Bool),
                UnOp::Neg => self.infer(expr),
            },
            Expr::LogicAnd(_) | Expr::LogicOr(_) => Ok(Type::Bool),
            Expr::Call { callee, .. } => {
                let sig = self.functions.get(callee).ok_or_else(|| {
                    Error::Codegen(format!("call to undefined function `{}`", callee))
                })?;
                sig.return_type.clone().ok_or_else(|| {
                    Error::Codegen(format!(
                        "function `{}` returns no value but its result is used",
                        callee
                    ))
                })
            }
            Expr::Input => Ok(Type::Deshnash),
            Expr::ArrayLit(elems) => {
                if elems.is_empty() {
                    return Err(Error::Codegen(
                        "empty array literal `[]` needs a type annotation; \
                         its element type can't be inferred on its own"
                            .into(),
                    ));
                }
                let t = self.infer(&elems[0])?;
                Ok(Type::Array(Box::new(t)))
            }
            Expr::Index { target, .. } => {
                let t = self.infer(target)?;
                match t {
                    Type::Array(inner) => Ok(*inner),
                    other => Err(Error::Codegen(format!(
                        "cannot index into non-array type {}",
                        type_name(&other)
                    ))),
                }
            }
            Expr::Baram(_) => Ok(Type::Terah),
            Expr::ParseTerah(_) => Ok(Type::Terah),
            Expr::ParseDaqosh(_) => Ok(Type::Daqosh),
            Expr::ToTerah(_) => Ok(Type::Terah),
            Expr::ToDaqosh(_) => Ok(Type::Daqosh),
            Expr::Pop(name) => {
                let arr_ty = self.lookup(name).ok_or_else(|| {
                    Error::Codegen(format!("pop on undefined variable `{}`", name))
                })?;
                match arr_ty {
                    Type::Array(inner) => Ok(*inner),
                    other => Err(Error::Codegen(format!(
                        "`pop` needs an array, but `{}` is {}",
                        name,
                        type_name(&other)
                    ))),
                }
            }
        }
    }

    // --- scope management ---
    fn push_scope(&mut self) {
        self.scopes.push(HashMap::new());
    }
    fn pop_scope(&mut self) {
        self.scopes.pop();
    }
    fn declare(&mut self, name: &str, ty: Type) {
        self.scopes
            .last_mut()
            .expect("no active scope")
            .insert(name.to_string(), ty);
    }
    fn lookup(&self, name: &str) -> Option<Type> {
        for scope in self.scopes.iter().rev() {
            if let Some(t) = scope.get(name) {
                return Some(t.clone());
            }
        }
        None
    }

    // --- output helpers ---
    fn write(&mut self, s: &str) {
        self.out.push_str(s);
    }
    fn writeln(&mut self, s: &str) {
        self.out.push_str(s);
        self.out.push('\n');
    }
    fn write_indent(&mut self) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
    }
}

/// If `b` is a single-stmt block containing only an `If`, return its pieces.
/// This is the shape the parser produces for `khi nagah sanna` and lets the
/// backend re-emit `else if` instead of `else { if ... }`.
fn as_chained_if(b: &Block) -> Option<(&Expr, &Block, Option<&Block>)> {
    if b.stmts.len() != 1 {
        return None;
    }
    match &b.stmts[0] {
        Stmt::If {
            cond,
            then_block,
            else_block,
        } => Some((cond, then_block, else_block.as_ref())),
        _ => None,
    }
}

/// C type name for a mott type. Arrays produce per-element-type struct
/// names like `mott_arr_terah` that are declared in the runtime header.
fn type_to_c(t: &Type) -> String {
    match t {
        Type::Terah => "int64_t".into(),
        Type::Daqosh => "double".into(),
        Type::Bool => "bool".into(),
        Type::Deshnash => "mott_str".into(),
        Type::Array(inner) => match inner.as_ref() {
            Type::Terah => "mott_arr_terah".into(),
            Type::Daqosh => "mott_arr_daqosh".into(),
            Type::Bool => "mott_arr_bool".into(),
            Type::Deshnash => "mott_arr_deshnash".into(),
            Type::Array(_) => "mott_arr_nested".into(),
            // ^ Unused today — nested arrays are rejected before we
            // get here, but keeping the arm so the match is exhaustive.
        },
    }
}

/// Mott-language type name for diagnostics.
fn type_name(t: &Type) -> String {
    match t {
        Type::Terah => "terah".into(),
        Type::Daqosh => "daqosh".into(),
        Type::Bool => "bool".into(),
        Type::Deshnash => "deshnash".into(),
        Type::Array(inner) => format!("[{}]", type_name(inner)),
    }
}

/// Name of the runtime constructor for an array whose element type is `t`.
fn array_ctor_name(t: &Type) -> &'static str {
    match t {
        Type::Terah => "mott_arr_terah_new",
        Type::Daqosh => "mott_arr_daqosh_new",
        Type::Bool => "mott_arr_bool_new",
        Type::Deshnash => "mott_arr_deshnash_new",
        Type::Array(_) => "mott_arr_nested_new", // unreachable today
    }
}

fn array_push_name(t: &Type) -> &'static str {
    match t {
        Type::Terah => "mott_arr_terah_push",
        Type::Daqosh => "mott_arr_daqosh_push",
        Type::Bool => "mott_arr_bool_push",
        Type::Deshnash => "mott_arr_deshnash_push",
        Type::Array(_) => "mott_arr_nested_push", // unreachable today
    }
}

fn array_pop_name(t: &Type) -> &'static str {
    match t {
        Type::Terah => "mott_arr_terah_pop",
        Type::Daqosh => "mott_arr_daqosh_pop",
        Type::Bool => "mott_arr_bool_pop",
        Type::Deshnash => "mott_arr_deshnash_pop",
        Type::Array(_) => "mott_arr_nested_pop", // unreachable today
    }
}

fn bin_op_str(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => " + ",
        BinOp::Sub => " - ",
        BinOp::Mul => " * ",
        BinOp::Div => " / ",
        BinOp::Mod => " % ",
        BinOp::Eq => " == ",
        BinOp::NotEq => " != ",
        BinOp::Lt => " < ",
        BinOp::Le => " <= ",
        BinOp::Gt => " > ",
        BinOp::Ge => " >= ",
    }
}

/// Render `s` as a C double-quoted string literal. UTF-8 bytes outside
/// printable ASCII are emitted as `\xNN`, which works because mott source
/// is UTF-8 and we never split a multibyte sequence.
fn c_string_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for b in s.bytes() {
        match b {
            b'\\' => out.push_str("\\\\"),
            b'"' => out.push_str("\\\""),
            b'\n' => out.push_str("\\n"),
            b'\t' => out.push_str("\\t"),
            b'\r' => out.push_str("\\r"),
            0x20..=0x7e => out.push(b as char),
            _ => {
                // Hex-escape followed by a string-break prevents the next ASCII
                // digit from being absorbed into the \x escape.
                let _ = write!(out, "\\x{:02x}\"\"", b);
            }
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn compile(src: &str) -> Result<String> {
        let tokens = Lexer::new(src).tokenize().expect("lex");
        let program = Parser::new(tokens).parse().expect("parse");
        CBackend.emit(&program)
    }

    fn compile_ok(src: &str) -> String {
        compile(src).expect("codegen should succeed")
    }

    #[test]
    fn hello_world_produces_main() {
        let c = compile_ok("fnc kort() { yazde(\"Salam\"); }");
        assert!(c.contains("int main(void)"), "got:\n{}", c);
        assert!(c.contains("mott_yazde_deshnash"), "got:\n{}", c);
        assert!(c.contains("MOTT_STR_LIT(\"Salam\")"), "got:\n{}", c);
        assert!(c.contains("return 0;"), "got:\n{}", c);
    }

    #[test]
    fn int_let_and_arithmetic() {
        let c = compile_ok("fnc kort() { xilit x = 5; xilit y: terah = x + 3; yazde(y); }");
        assert!(c.contains("int64_t x ="));
        assert!(c.contains("int64_t y ="));
        assert!(c.contains("mott_yazde_terah(y)"));
    }

    #[test]
    fn interpolation_emits_str_build() {
        let c = compile_ok("fnc kort() { xilit x = 5; yazde(\"x = {x}\"); }");
        assert!(c.contains("mott_str_build"), "got:\n{}", c);
        assert!(c.contains("mott_str_from_terah(x)"), "got:\n{}", c);
        assert!(c.contains("MOTT_STR_LIT(\"x = \")"), "got:\n{}", c);
    }

    #[test]
    fn if_else_and_while() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit i: terah = 0;
    cqachunna (i < 3) {
        nagah sanna (i == 1) {
            yazde("one");
        } khi {
            yazde("other");
        }
        i = i + 1;
    }
}
"#,
        );
        assert!(c.contains("while ("));
        assert!(c.contains("if ("));
        assert!(c.contains("} else {"));
    }

    #[test]
    fn khi_nagah_sanna_emits_else_if() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit x: terah = 1;
    nagah sanna (x == 1) {
        yazde("one");
    } khi nagah sanna (x == 2) {
        yazde("two");
    } khi nagah sanna (x == 3) {
        yazde("three");
    } khi {
        yazde("other");
    }
}
"#,
        );
        // Should emit idiomatic `else if` — not nested `else { if ... }`.
        assert!(
            c.contains("} else if ("),
            "expected idiomatic `else if`, got:\n{}",
            c
        );
        // Exactly one final `} else {` for the terminal branch.
        assert_eq!(c.matches("} else {").count(), 1, "got:\n{}", c);
        // No spurious nested brace-wrapped if.
        assert!(
            !c.contains("} else {\n            if ("),
            "chain should not produce nested blocks, got:\n{}",
            c
        );
    }

    #[test]
    fn logic_and_becomes_cc_and() {
        let c = compile_ok(
            "fnc kort() { xilit x: terah = 5; nagah sanna (x > 0 a, x < 10 a) { yazde(\"ok\"); } }",
        );
        assert!(c.contains(" && "), "got:\n{}", c);
    }

    #[test]
    fn logic_or_becomes_cc_or() {
        let c = compile_ok(
            "fnc kort() { xilit x: terah = 5; nagah sanna (x < 0 ya x > 10) { yazde(\"out\"); } }",
        );
        assert!(c.contains(" || "), "got:\n{}", c);
    }

    #[test]
    fn function_with_params_emits_forward_decl() {
        let c = compile_ok(
            r#"
fnc add(x: terah, y: terah) -> terah {
    yuxadalo x + y;
}
fnc kort() {
    xilit z = add(2, 3);
    yazde(z);
}
"#,
        );
        assert!(c.contains("int64_t add(int64_t x, int64_t y);"), "got:\n{}", c);
        assert!(c.contains("int64_t add(int64_t x, int64_t y) {"), "got:\n{}", c);
        assert!(c.contains("add(((int64_t)2LL), ((int64_t)3LL))"), "got:\n{}", c);
    }

    #[test]
    fn type_mismatch_in_let_errors() {
        let err = compile("fnc kort() { xilit x: terah = baqderg; }").unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("type mismatch"), "got: {}", msg);
    }

    #[test]
    fn undefined_variable_errors() {
        let err = compile("fnc kort() { yazde(nope); }").unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("undefined variable"), "got: {}", msg);
    }

    #[test]
    fn kort_with_params_is_rejected() {
        let err = compile("fnc kort(x: terah) { yazde(x); }").unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("kort"), "got: {}", msg);
    }

    #[test]
    fn non_bool_condition_is_rejected() {
        let err = compile("fnc kort() { xilit x = 1; nagah sanna (x) { yazde(\"hi\"); } }")
            .unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("must be bool"), "got: {}", msg);
    }

    #[test]
    fn sac_and_khida_emit_break_continue() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit i: terah = 0;
    cqachunna (i < 10) {
        nagah sanna (i == 5) {
            sac;
        }
        i = i + 1;
        khida;
    }
}
"#,
        );
        assert!(c.contains("break;"), "got:\n{}", c);
        assert!(c.contains("continue;"), "got:\n{}", c);
    }

    #[test]
    fn sac_outside_loop_errors() {
        let err = compile("fnc kort() { sac; }").unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("outside of"), "got: {}", msg);
    }

    #[test]
    fn khida_outside_loop_errors() {
        let err = compile("fnc kort() { khida; }").unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("outside of"), "got: {}", msg);
    }

    #[test]
    fn sac_inside_if_inside_loop_is_ok() {
        // An if nested in a loop must still allow `sac`.
        let c = compile_ok(
            r#"
fnc kort() {
    xilit i: terah = 0;
    cqachunna (i < 10) {
        nagah sanna (i > 3) {
            sac;
        }
        i = i + 1;
    }
}
"#,
        );
        assert!(c.contains("break;"));
    }

    #[test]
    fn string_equality_lowers_to_runtime_call() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit name: deshnash = "salam"
    nagah sanna name == "salam" {
        yazde("hi")
    }
}
"#,
        );
        assert!(c.contains("mott_str_eq("), "got:\n{}", c);
        // Importantly: should NOT emit bare `name == "salam"` infix on
        // mott_str structs — that would be nonsense C.
        assert!(!c.contains("name == MOTT_STR_LIT"), "got:\n{}", c);
    }

    #[test]
    fn string_inequality_emits_negated_runtime_call() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit name: deshnash = "salam"
    nagah sanna name != "marshalla" {
        yazde("not marshalla")
    }
}
"#,
        );
        assert!(c.contains("(!mott_str_eq("), "got:\n{}", c);
    }

    #[test]
    fn string_eq_with_non_string_is_type_error() {
        let err = compile(
            r#"
fnc kort() {
    xilit s: deshnash = "x"
    nagah sanna s == 5 {
        yazde("nope")
    }
}
"#,
        )
        .unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("type mismatch"), "got: {}", msg);
    }

    #[test]
    fn string_ordering_is_still_rejected() {
        // `<` / `>` on strings remains unsupported — we only added equality.
        let err = compile(
            r#"
fnc kort() {
    xilit lhs: deshnash = "x"
    xilit rhs: deshnash = "y"
    nagah sanna lhs < rhs {
        yazde("x")
    }
}
"#,
        )
        .unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("numeric"), "got: {}", msg);
    }

    #[test]
    fn esha_emits_mott_input_call_typed_as_deshnash() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit line: deshnash = esha()
    yazde(line)
}
"#,
        );
        assert!(c.contains("mott_input()"), "got:\n{}", c);
        // Must be stored as mott_str (deshnash), not int64 or anything else.
        assert!(c.contains("mott_str line = "), "got:\n{}", c);
    }

    #[test]
    fn esha_into_wrong_type_is_rejected() {
        let err = compile(
            r#"
fnc kort() {
    xilit n: terah = esha()
}
"#,
        )
        .unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("type mismatch"), "got: {}", msg);
    }

    #[test]
    fn array_literal_emits_runtime_constructor() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit nums: [terah] = [1, 2, 3]
    yazde(baram(nums))
}
"#,
        );
        assert!(c.contains("mott_arr_terah nums = "), "got:\n{}", c);
        assert!(c.contains("mott_arr_terah_new(3"), "got:\n{}", c);
        assert!(c.contains("(int64_t)(nums.len)"), "got:\n{}", c);
    }

    #[test]
    fn for_each_array_emits_indexed_loop() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit nums: [terah] = [10, 20, 30]
    yallalc x chu nums {
        yazde(x)
    }
}
"#,
        );
        assert!(c.contains("__mott_arr.len"), "got:\n{}", c);
        assert!(c.contains("int64_t x = __mott_arr.data[__mott_i]"), "got:\n{}", c);
    }

    #[test]
    fn for_each_range_emits_counting_loop() {
        let c = compile_ok(
            r#"
fnc kort() {
    yallalc i chu 0..5 {
        yazde(i)
    }
}
"#,
        );
        assert!(c.contains("for (int64_t i = "), "got:\n{}", c);
        assert!(c.contains("i++"), "got:\n{}", c);
    }

    #[test]
    fn parse_terah_emits_runtime_call() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit s: deshnash = "42"
    xilit n: terah = parse_terah(s)
    yazde(n)
}
"#,
        );
        assert!(c.contains("mott_parse_terah(s)"), "got:\n{}", c);
        assert!(c.contains("int64_t n = "), "got:\n{}", c);
    }

    #[test]
    fn parse_daqosh_emits_runtime_call() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit s: deshnash = "3.14"
    xilit x: daqosh = parse_daqosh(s)
    yazde(x)
}
"#,
        );
        assert!(c.contains("mott_parse_daqosh(s)"), "got:\n{}", c);
        assert!(c.contains("double x = "), "got:\n{}", c);
    }

    #[test]
    fn parse_terah_on_non_string_is_rejected() {
        let err = compile(
            r#"
fnc kort() {
    xilit n: terah = parse_terah(42)
}
"#,
        )
        .unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("needs a deshnash"), "got: {}", msg);
    }

    #[test]
    fn parse_daqosh_on_non_string_is_rejected() {
        let err = compile(
            r#"
fnc kort() {
    xilit x: daqosh = parse_daqosh(baqderg)
}
"#,
        )
        .unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("needs a deshnash"), "got: {}", msg);
    }

    #[test]
    fn parse_result_type_mismatch_is_caught() {
        // parse_terah returns terah; storing in a daqosh variable is a
        // type error, caught at the Let site.
        let err = compile(
            r#"
fnc kort() {
    xilit x: daqosh = parse_terah("42")
}
"#,
        )
        .unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("type mismatch"), "got: {}", msg);
    }

    #[test]
    fn to_terah_from_daqosh_emits_cast() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit x: daqosh = 3.7
    xilit n: terah = to_terah(x)
    yazde(n)
}
"#,
        );
        assert!(c.contains("((int64_t)(x))"), "got:\n{}", c);
        assert!(c.contains("int64_t n = "), "got:\n{}", c);
    }

    #[test]
    fn to_daqosh_from_terah_emits_cast() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit n: terah = 42
    xilit x: daqosh = to_daqosh(n)
    yazde(x)
}
"#,
        );
        assert!(c.contains("((double)(n))"), "got:\n{}", c);
        assert!(c.contains("double x = "), "got:\n{}", c);
    }

    #[test]
    fn to_terah_on_terah_is_noop_cast() {
        // Allowed but pointless — we don't special-case it, just emit the
        // cast. Rationale: same rule as `x as i64` in Rust on an `i64`.
        let c = compile_ok(
            r#"
fnc kort() {
    xilit n: terah = 5
    xilit m: terah = to_terah(n)
    yazde(m)
}
"#,
        );
        assert!(c.contains("((int64_t)(n))"), "got:\n{}", c);
    }

    #[test]
    fn to_terah_on_non_numeric_is_rejected() {
        let err = compile(
            r#"
fnc kort() {
    xilit n: terah = to_terah(baqderg)
}
"#,
        )
        .unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("numeric"), "got: {}", msg);
    }

    #[test]
    fn to_daqosh_on_string_is_rejected() {
        let err = compile(
            r#"
fnc kort() {
    xilit s: deshnash = "42"
    xilit x: daqosh = to_daqosh(s)
}
"#,
        )
        .unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("numeric"), "got: {}", msg);
    }

    #[test]
    fn push_emits_runtime_call_with_address() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit nums: [terah] = [1, 2]
    push(nums, 3)
}
"#,
        );
        assert!(c.contains("mott_arr_terah_push(&nums, "), "got:\n{}", c);
    }

    #[test]
    fn pop_emits_runtime_call_with_address() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit nums: [terah] = [1, 2, 3]
    xilit last: terah = pop(nums)
    yazde(last)
}
"#,
        );
        assert!(c.contains("mott_arr_terah_pop(&nums)"), "got:\n{}", c);
    }

    #[test]
    fn push_type_mismatch_rejected() {
        let err = compile(
            r#"
fnc kort() {
    xilit nums: [terah] = [1]
    push(nums, baqderg)
}
"#,
        )
        .unwrap_err();
        assert!(format!("{}", err).contains("push type mismatch"));
    }

    #[test]
    fn push_on_non_array_rejected() {
        let err = compile(
            r#"
fnc kort() {
    xilit x: terah = 5
    push(x, 1)
}
"#,
        )
        .unwrap_err();
        assert!(format!("{}", err).contains("needs an array"));
    }

    #[test]
    fn push_on_parameter_rejected() {
        // Mott has no references yet; aliasing makes push-to-parameter UB.
        // Catch it at codegen with a clear message.
        let err = compile(
            r#"
fnc helper(arr: [terah]) {
    push(arr, 1)
}
fnc kort() {
    xilit nums: [terah] = [1]
    helper(nums)
}
"#,
        )
        .unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("function parameter"), "got: {}", msg);
    }

    #[test]
    fn pop_on_parameter_rejected() {
        let err = compile(
            r#"
fnc helper(arr: [terah]) -> terah {
    yuxadalo pop(arr)
}
fnc kort() {
    xilit nums: [terah] = [1]
    yazde(helper(nums))
}
"#,
        )
        .unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("function parameter"), "got: {}", msg);
    }

    #[test]
    fn empty_array_literal_with_annotation_emits_zero_new() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit nums: [terah] = []
    push(nums, 1)
}
"#,
        );
        assert!(c.contains("mott_arr_terah_new(0, NULL)"), "got:\n{}", c);
    }

    #[test]
    fn empty_array_literal_without_annotation_errors() {
        let err = compile(
            r#"
fnc kort() {
    xilit nums = []
}
"#,
        )
        .unwrap_err();
        assert!(format!("{}", err).contains("type annotation"));
    }

    #[test]
    fn to_daqosh_enables_real_float_division() {
        // The motivating use case: sum / count as float. Without to_daqosh
        // this would have been integer division.
        let c = compile_ok(
            r#"
fnc kort() {
    xilit total: terah = 78
    xilit n: terah = 10
    xilit avg: daqosh = to_daqosh(total) / to_daqosh(n)
    yazde(avg)
}
"#,
        );
        assert!(c.contains("((double)(total))"), "got:\n{}", c);
        assert!(c.contains("((double)(n))"), "got:\n{}", c);
    }

    #[test]
    fn parse_can_be_chained_with_esha() {
        // parse_terah(esha()) — the bread-and-butter use case. Just check
        // it type-checks and emits both calls; runtime behavior is covered
        // by the sum-input integration example.
        let c = compile_ok(
            r#"
fnc kort() {
    xilit n: terah = parse_terah(esha())
    yazde(n)
}
"#,
        );
        assert!(c.contains("mott_parse_terah(mott_input())"), "got:\n{}", c);
    }

    #[test]
    fn baram_on_string_works() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit s: deshnash = "salam"
    yazde(baram(s))
}
"#,
        );
        assert!(c.contains("(int64_t)(s.len)"), "got:\n{}", c);
    }

    #[test]
    fn array_index_assignment() {
        let c = compile_ok(
            r#"
fnc kort() {
    xilit nums: [terah] = [1, 2, 3]
    nums[0] = 99
}
"#,
        );
        assert!(c.contains("nums.data["), "got:\n{}", c);
    }

    #[test]
    fn array_element_type_mismatch_is_rejected() {
        let err = compile(
            r#"
fnc kort() {
    xilit nums: [terah] = [1, 2, baqderg]
}
"#,
        )
        .unwrap_err();
        assert!(format!("{}", err).contains("expected terah"));
    }

    #[test]
    fn yallalc_over_non_array_is_rejected() {
        let err = compile(
            r#"
fnc kort() {
    xilit x: terah = 5
    yallalc i chu x {
        yazde(i)
    }
}
"#,
        )
        .unwrap_err();
        assert!(format!("{}", err).contains("needs an array"));
    }

    #[test]
    fn sac_in_separate_function_is_scoped() {
        // `cqachunna` in helper shouldn't let `sac` escape into `kort`.
        let err = compile(
            r#"
fnc helper() {
    cqachunna (baqderg) { sac; }
}
fnc kort() {
    sac;
}
"#,
        )
        .unwrap_err();
        let msg = format!("{}", err);
        assert!(msg.contains("outside of"), "got: {}", msg);
    }
}
